### ISSUE TITLE
Sugestão de melhorias 

### ISSUE THREAD

**Issue by jessicaguiot** [pedrosousa27/Aux#3]
Arquivo: aux.swift
Sugestão:  tratar as variáveis como um optional, porque se eu não digito nada, o programa quebra, não está preparado para não receber nada. 

Exemplo: `

        public func process(arg: String? = " ") {
        var cmd: String?
        var content: String?
        
        if var args = arg?.split(separator: " ") {
            cmd = String(args.first ?? " ")
            if args.first != nil {
                args.remove(at: 0)
            }
            content = args.joined(separator: " ")
        }
        
        
        
        switch cmd ?? " " {
        case "list":
            listEnvironment()
        case "create":
            createEnvironment(env: content ?? " ")
        case "run":
            executeEnvironment(env: content ?? " ")
        case "delete":
            deleteEnvironment(env: content ?? " ")
        case "exit":
            exit(0)
        default:
            print("Error: Command not recognized by the system.")
        }
    }
    `

**Comment by pedro0x53** [comment]
Bug corrigido!
Ao invés de tratar a String como Optional, optei por trata-lá antes da chamada do método **process**, por conta de escopo.
Se possível checar a Branch [dev](https://github.com/pedrosousa27/Aux/tree/dev) para validação do mesmo.
