### ISSUE TITLE
Sugestão de melhoria

### ISSUE THREAD

**Issue by lidianegb** [pedrosousa27/Aux#4]
Lidiane / Paulo

Arquivo: aux.swift

Sugiro incluir o comando "help", pra listar os comandos disponíveis pela aplicação e explicando o que cada comando faz. É bastante útil quando a gente esquece o nome de um comando.

Gostei muito do trabalho de vocês, parabéns!

**Comment by pedro0x53** [comment]
Comando adicionado! Obrigado pelo feedback.
Se possível validar a alteração feita na branch [dev](https://github.com/pedrosousa27/Aux/tree/dev).
