### ISSUE TITLE
Organização e listagem de apps nas mesas

### ISSUE THREAD

**Issue by LucasAgosti** [pedrosousa27/Aux#6]
**Sugestão**: Senti falta de apenas uma seção "help", como já foi citado e de uma melhor visualização de qual/quais aplicações estão abertas nas mesas, podendo ser colocadas na parte de listagem, onde mostraria o nome da mesa e os apps que estão abertos nas mesmas, isso poderia evitar situações em que eu delete uma mesa e por acaso eu feche aplicações indesejadas.

**Comment by LucasAgosti** [comment]
No geral ta tudo incrível, parabéns

**Comment by pedro0x53** [comment]
Valeu pelo feedback!!
Melhoria adicionada, se possível testar a branch [dev](https://github.com/pedrosousa27/Aux/tree/dev) para finalizar essa issue.
