### ISSUE TITLE
Sugestão de melhoria

### ISSUE THREAD

**Issue by ronaldogomes96** [pedrosousa27/Aux#7]
Dupla: Beatriz / Ronaldo

Arquivo:
main.swift

Descrição:
Quando eu abro o programa, ele não aparece nada. Seria interessante pelo menos um menu inicial simples mostrando os nomes das funcionalidades dele, ate pra mostrar que ele esta funcionando e não travou, porque não aparece nada na tela. Fora isso, ta muito bom, parabéns!

**Comment by pedro0x53** [comment]
Duplicated of #5

**Comment by pedro0x53** [comment]
Alterações feitas.
Se possível validar na branch [dev](https://github.com/pedrosousa27/Aux/tree/dev).
